services:
  db:
    image: postgres:18.1
    container_name: prisma-news-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma_news_dev
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql

volumes:
  postgres_data:
